# -*- coding: utf-8 -*-
"""Group07_Code_DecisionTree&RandomForest

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pAoRsVQoYR6fxih4PjsVt_m6ynfsJP5q

#PHẦN TIỀN XỬ LÝ DỮ LIỆU

## 🟦 Hình 1: Import thư viện
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay

"""Trong bước đầu tiên, chương trình tiến hành import các thư viện cần thiết để phục vụ cho quá trình xử lý dữ liệu và xây dựng mô hình học máy.

Cụ thể, các thư viện được sử dụng bao gồm:

- pandas, numpy: dùng để xử lý và thao tác với dữ liệu dạng bảng  
- matplotlib: hỗ trợ trực quan hóa dữ liệu  
- train_test_split: dùng để chia dữ liệu thành tập huấn luyện và tập kiểm tra  
- DecisionTreeClassifier, RandomForestClassifier: các thuật toán học máy được sử dụng trong bài toán  
- accuracy_score, confusion_matrix, classification_report: dùng để đánh giá mô hình  
- plot_tree: dùng để vẽ cây quyết định  

-> Nhận xét:  
Việc import đầy đủ thư viện giúp chuẩn bị môi trường làm việc hoàn chỉnh, đảm bảo các bước xử lý và xây dựng mô hình được thực hiện thuận lợi.

## 🟦 Hình 2: Đọc dữ liệu và tạo nhãn
"""

df = pd.read_csv("movielens_full_converted.csv")

# Tạo nhãn: thích = 1, không thích = 0
df["label"] = df["rating"].apply(lambda x: 1 if x >= 4 else 0)

print("Kích thước dữ liệu:", df.shape)
df.head()

"""Sau khi chuẩn bị môi trường làm việc, chương trình tiến hành đọc dữ liệu từ file `movielens_full_converted.csv` bằng hàm `pd.read_csv()` và lưu vào biến `df`.

Tiếp theo, nhóm thực hiện bước chuyển đổi dữ liệu bằng cách tạo thêm một cột mới tên là `label`, dựa trên giá trị của cột `rating`.

Cụ thể:
- Nếu giá trị rating lớn hơn hoặc bằng 4.0 thì gán label = 1, thể hiện rằng người dùng thích phim.
- Nếu giá trị rating nhỏ hơn 4.0 thì gán label = 0, thể hiện rằng người dùng không thích phim.

-> Nhận xét:  
Bước này có ý nghĩa rất quan trọng vì giúp chuyển bài toán từ dạng dự đoán điểm số (regression) sang dạng phân loại nhị phân (classification). Điều này giúp các thuật toán như Decision Tree và Random Forest có thể áp dụng hiệu quả hơn trong việc dự đoán.

## 🟦 Hình 3: Chọn các cột cần thiết
"""

df = df[["userId", "movieId", "rating", "genres", "label"]].copy()

# Điền giá trị trống cho genres nếu có
df["genres"] = df["genres"].fillna("")

"""Sau khi dữ liệu được nạp vào, chương trình tiến hành chọn lọc các cột cần thiết phục vụ cho bài toán.

Các cột được giữ lại bao gồm:
- userId: mã định danh của người dùng.
- movieId: mã định danh của bộ phim.
- rating: điểm đánh giá mà người dùng cho phim.
- genres: thể loại của phim.
- label: nhãn mục tiêu đã được tạo ở bước trước.

Ngoài ra, cột `genres` được xử lý để loại bỏ các giá trị thiếu bằng cách thay thế bằng chuỗi rỗng, nhằm tránh lỗi trong các bước xử lý tiếp theo.

-> Nhận xét:  
Việc loại bỏ các cột không cần thiết như `title`, `tag`, `timestamp` giúp giảm độ phức tạp của dữ liệu, loại bỏ nhiễu và giúp mô hình tập trung vào các đặc trưng quan trọng hơn.

## 🟦 Hình 4: Chia dữ liệu train/test
"""

train_df, test_df = train_test_split(
    df,
    test_size=0.2,
    random_state=42,
    stratify=df["label"]
)

print("Train:", train_df.shape)
print("Test :", test_df.shape)

"""Ở bước này, dữ liệu được chia thành hai phần:
- 80% dữ liệu được sử dụng để huấn luyện mô hình (train).
- 20% dữ liệu được sử dụng để kiểm tra mô hình (test).

Ngoài ra, tham số `stratify` được sử dụng để đảm bảo rằng tỷ lệ giữa hai lớp (thích và không thích) được giữ nguyên trong cả tập train và tập test.

-> Nhận xét:  
Việc chia dữ liệu là một bước rất quan trọng trong học máy, giúp đánh giá khả năng dự đoán của mô hình trên dữ liệu chưa từng thấy.  
Sử dụng stratify giúp tránh tình trạng mất cân bằng dữ liệu giữa các lớp, từ đó đảm bảo kết quả đánh giá chính xác và đáng tin cậy hơn.

## 🟦 Hình 5: Tạo đặc trưng thống kê
"""

# Trung bình rating theo user, chỉ tính trên train
user_avg_train = train_df.groupby("userId")["rating"].mean()

# Trung bình rating theo movie, chỉ tính trên train
movie_avg_train = train_df.groupby("movieId")["rating"].mean()

# Map vào train
train_df["user_avg_rating"] = train_df["userId"].map(user_avg_train)
train_df["movie_avg_rating"] = train_df["movieId"].map(movie_avg_train)

# Map vào test
test_df["user_avg_rating"] = test_df["userId"].map(user_avg_train)
test_df["movie_avg_rating"] = test_df["movieId"].map(movie_avg_train)

"""Sau khi chia dữ liệu, nhóm tiến hành xây dựng các đặc trưng mới từ tập train.

Cụ thể, hai đặc trưng được tạo ra là:
- user_avg_rating: điểm đánh giá trung bình của mỗi người dùng.
- movie_avg_rating: điểm đánh giá trung bình của mỗi bộ phim.

Các giá trị này được tính toán dựa trên tập train, sau đó được ánh xạ (map) sang cả tập train và tập test.

-> Nhận xét:  
Đây là bước cải tiến rất quan trọng, giúp mô hình học được hành vi đánh giá của người dùng và xu hướng đánh giá của phim.  
So với việc sử dụng trực tiếp `userId` và `movieId`, các đặc trưng này mang ý nghĩa thực tế hơn và giúp mô hình tổng quát hóa tốt hơn.

## 🟦 Hình 6: Xử lý giá trị thiếu
"""

global_user_avg = train_df["rating"].mean()
global_movie_avg = train_df["rating"].mean()

train_df["user_avg_rating"] = train_df["user_avg_rating"].fillna(global_user_avg)
train_df["movie_avg_rating"] = train_df["movie_avg_rating"].fillna(global_movie_avg)

test_df["user_avg_rating"] = test_df["user_avg_rating"].fillna(global_user_avg)
test_df["movie_avg_rating"] = test_df["movie_avg_rating"].fillna(global_movie_avg)

"""Trong quá trình ánh xạ dữ liệu, có thể xảy ra trường hợp một số `userId` hoặc `movieId` trong tập test không xuất hiện trong tập train.

Điều này dẫn đến việc các giá trị `user_avg_rating` hoặc `movie_avg_rating` bị thiếu.

Do đó, chương trình tiến hành xử lý các giá trị thiếu bằng cách thay thế bằng giá trị trung bình chung của toàn bộ dữ liệu.

-> Nhận xét:  
Việc xử lý giá trị thiếu giúp đảm bảo dữ liệu đầy đủ trước khi đưa vào mô hình, tránh lỗi trong quá trình huấn luyện và dự đoán.  
Đồng thời giúp mô hình vẫn có thể hoạt động ổn định khi gặp dữ liệu mới chưa từng xuất hiện trước đó.

## 🟦 Hình 7: One-hot encoding cho genres
"""

train_genres = train_df["genres"].str.get_dummies(sep="|")
test_genres = test_df["genres"].str.get_dummies(sep="|")

# Đồng bộ cột giữa train và test
train_genres, test_genres = train_genres.align(test_genres, join="left", axis=1, fill_value=0)
test_genres = test_genres.fillna(0)

"""Cột `genres` ban đầu là dữ liệu dạng chuỗi (text), trong đó mỗi phim có thể thuộc nhiều thể loại khác nhau, được phân tách bằng dấu `|`.

Chương trình sử dụng phương pháp one-hot encoding để chuyển đổi dữ liệu này sang dạng số.

Kết quả:
- Mỗi thể loại sẽ trở thành một cột riêng.
- Nếu phim thuộc thể loại đó thì giá trị bằng 1.
- Nếu không thuộc thì giá trị bằng 0.

-> Nhận xét:  
Đây là bước bắt buộc vì các thuật toán học máy chỉ có thể xử lý dữ liệu dạng số.  
Việc chuyển đổi này giúp mô hình hiểu được thông tin về thể loại phim và sử dụng chúng để đưa ra dự đoán chính xác hơn.

## 🟦 Hình 8: Tạo tập dữ liệu huấn luyện
"""

X_train = pd.concat(
    [train_df[["user_avg_rating", "movie_avg_rating"]].reset_index(drop=True),
     train_genres.reset_index(drop=True)],
    axis=1)
X_test = pd.concat(
    [test_df[["user_avg_rating", "movie_avg_rating"]].reset_index(drop=True),
     test_genres.reset_index(drop=True)],
    axis=1)
y_train = train_df["label"].reset_index(drop=True)
y_test = test_df["label"].reset_index(drop=True)
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)
X_train.head()

"""Sau khi hoàn tất các bước xử lý, chương trình tiến hành xây dựng tập dữ liệu đầu vào cho mô hình.

Cụ thể:
- X (features) bao gồm:
  - user_avg_rating
  - movie_avg_rating
  - các cột thể loại phim sau khi đã mã hóa

- y (label) là cột `label`, thể hiện mục tiêu cần dự đoán.

-> Nhận xét:  
Tại bước này, dữ liệu đã được xử lý hoàn chỉnh và phù hợp để đưa vào các mô hình học máy.  
Các đặc trưng được sử dụng đều mang ý nghĩa thực tế, giúp mô hình học tốt hơn và cải thiện độ chính xác so với cách làm ban đầu.

# PHẦN DECISION TREE

## 🟦 Hình 9: Xây dựng mô hình Decision Tree
"""

dt_model = DecisionTreeClassifier(
    criterion="gini",
    max_depth=10,
    min_samples_split=5,
    min_samples_leaf=10,
    class_weight="balanced",
    random_state=42
)

dt_model.fit(X_train, y_train)

"""Sau khi dữ liệu đã được xử lý và chuẩn bị đầy đủ, nhóm tiến hành xây dựng mô hình Decision Tree.

Mô hình Decision Tree là một thuật toán học máy dạng cây, trong đó dữ liệu được phân chia thành các nhánh dựa trên điều kiện của các thuộc tính, từ đó đưa ra dự đoán cuối cùng.

Trong bài toán này, mô hình được khởi tạo với các tham số sau:

- criterion = "gini": sử dụng chỉ số Gini để đo mức độ hỗn loạn của dữ liệu tại mỗi node, từ đó quyết định cách chia nhánh tối ưu.
- max_depth = 10: giới hạn độ sâu tối đa của cây nhằm tránh việc cây phát triển quá lớn và gây ra hiện tượng overfitting.
- min_samples_split = 5: một node phải có ít nhất 5 mẫu thì mới được phép tiếp tục chia.
- min_samples_leaf = 10: mỗi node lá phải chứa ít nhất 10 mẫu để đảm bảo tính ổn định.
- class_weight = "balanced": tự động điều chỉnh trọng số của các lớp để tránh mất cân bằng dữ liệu.

Sau khi thiết lập các tham số, mô hình được huấn luyện bằng cách sử dụng tập dữ liệu train.

-> Nhận xét:  
Việc thiết lập các tham số phù hợp giúp mô hình tránh được việc học quá chi tiết dữ liệu huấn luyện, từ đó giảm nguy cơ overfitting và giúp mô hình hoạt động ổn định hơn.

## 🟦 Hình 10: Kết quả Decision Tree
"""

y_pred_dt = dt_model.predict(X_test)

dt_acc = accuracy_score(y_test, y_pred_dt)
print("Decision Tree Accuracy:", dt_acc)

dt_cm = confusion_matrix(y_test, y_pred_dt)
print("\nConfusion Matrix:\n", dt_cm)

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_dt))

"""Sau khi huấn luyện xong, mô hình được sử dụng để dự đoán trên tập dữ liệu test nhằm đánh giá hiệu quả.

Kết quả thu được như sau:
- Accuracy ≈ 0.70
- Các chỉ số Precision, Recall và F1-score của cả hai lớp đều xấp xỉ 0.70.

-> Nhận xét:  
Kết quả này cho thấy mô hình Decision Tree hoạt động khá tốt và có sự cân bằng giữa hai lớp “thích” và “không thích”.  
So với việc sử dụng trực tiếp các biến định danh trước đó, việc sử dụng các đặc trưng mới đã giúp cải thiện đáng kể độ chính xác của mô hình.

## 🟦 Hình 11: Ma trận nhầm lẫn
"""

disp = ConfusionMatrixDisplay(confusion_matrix=dt_cm, display_labels=["Dislike", "Like"])
disp.plot()
plt.title("Decision Tree - Confusion Matrix")
plt.show()

"""Để đánh giá chi tiết hơn khả năng phân loại của mô hình, nhóm sử dụng ma trận nhầm lẫn (confusion matrix).

Kết quả cho thấy:
- Số lượng dự đoán đúng lớp “không thích”: 7086
- Số lượng dự đoán đúng lớp “thích”: 7016
- Có 3366 trường hợp thực tế là “Không thích” nhưng bị dự đoán thành “Thích”.
- Có 2700 trường hợp thực tế là “Thích” nhưng bị dự đoán thành “Không thích”.

-> Nhận xét:  
Ma trận nhầm lẫn cho thấy mô hình đã phân biệt khá tốt giữa hai lớp, tuy nhiên vẫn còn một lượng nhầm lẫn nhất định, đặc biệt là xu hướng dự đoán nhầm từ “Không thích” sang “Thích”  
Điều này cho thấy bài toán dự đoán sở thích người dùng vẫn còn độ khó nhất định và chưa thể đạt độ chính xác tuyệt đối.

## 🟦 Hình 12: Vẽ cây quyết định
"""

plt.figure(figsize=(24, 12))
plot_tree(
    dt_model,
    feature_names=X_train.columns,
    class_names=["Dislike", "Like"],
    filled=True,
    fontsize=8,
    max_depth=3
)
plt.title("Decision Tree (hiển thị 3 mức đầu)")
plt.show()

"""Nhóm tiến hành trực quan hóa mô hình Decision Tree bằng cách sử dụng hàm `plot_tree`.

Do cây quyết định đầy đủ có kích thước rất lớn và khó quan sát, nên nhóm chỉ hiển thị 3 mức đầu tiên của cây để dễ dàng phân tích.

Trong cây quyết định:
- Mỗi node thể hiện một điều kiện phân chia dữ liệu dựa trên giá trị của một thuộc tính.
- Các nhánh thể hiện các hướng đi khác nhau tùy theo điều kiện.
- Màu sắc thể hiện lớp dự đoán (thích hoặc không thích).

-> Nhận xét:  
Một trong những ưu điểm lớn của Decision Tree là khả năng trực quan hóa, giúp người dùng dễ dàng hiểu được cách mà mô hình đưa ra quyết định.  
Tuy nhiên, nếu cây quá sâu thì sẽ trở nên phức tạp và khó diễn giải.

## 🟦 Hình 13: Độ quan trọng thuộc tính
"""

dt_importance = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": dt_model.feature_importances_
}).sort_values(by="Importance", ascending=False)

print(dt_importance.head(10))

top_dt = dt_importance.head(10)

plt.figure(figsize=(10, 6))
plt.barh(top_dt["Feature"], top_dt["Importance"])
plt.gca().invert_yaxis()
plt.xlabel("Importance")
plt.ylabel("Feature")
plt.title("Top 10 thuộc tính quan trọng - Decision Tree")
plt.show()

"""Sau khi huấn luyện, nhóm tiến hành tính toán độ quan trọng của các thuộc tính trong mô hình.

Kết quả cho thấy:
- movie_avg_rating có độ quan trọng cao nhất (khoảng 0.60)
- user_avg_rating đứng thứ hai (khoảng 0.38)
- Các thể loại phim như Action, Thriller, Drama… có ảnh hưởng nhưng nhỏ hơn nhiều

-> Nhận xét:  
Kết quả này cho thấy mô hình chủ yếu dựa vào xu hướng đánh giá của phim và hành vi đánh giá của người dùng để đưa ra dự đoán.  
Các đặc trưng này mang ý nghĩa thực tế hơn so với việc sử dụng trực tiếp các biến định danh như userId và movieId, giúp mô hình tổng quát hóa tốt hơn.

# PHẦN RANDOM FOREST

## 🟦 Hình 14: Xây dựng mô hình Random Forest
"""

rf_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    min_samples_split=5,
    min_samples_leaf=10,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

"""Sau khi hoàn thành mô hình Decision Tree, nhóm tiếp tục xây dựng mô hình Random Forest để so sánh và cải thiện kết quả.

Random Forest là thuật toán kết hợp nhiều cây quyết định, trong đó mỗi cây được huấn luyện trên một phần dữ liệu ngẫu nhiên khác nhau. Kết quả cuối cùng được xác định dựa trên nguyên tắc bỏ phiếu đa số.

Mô hình được thiết lập với các tham số:
- n_estimators = 200: sử dụng 200 cây quyết định
- max_depth = 10: giới hạn độ sâu mỗi cây
- min_samples_split = 5
- min_samples_leaf = 10
- class_weight = "balanced"

Sau đó, mô hình được huấn luyện trên tập dữ liệu train.

-> Nhận xét:  
Việc sử dụng nhiều cây quyết định giúp mô hình giảm overfitting và tăng tính ổn định.  
Random Forest thường cho kết quả tốt hơn Decision Tree vì không phụ thuộc vào một cây duy nhất.

## 🟦 Hình 15: Kết quả Random Forest
"""

y_pred_rf = rf_model.predict(X_test)

rf_acc = accuracy_score(y_test, y_pred_rf)
print("Random Forest Accuracy:", rf_acc)

rf_cm = confusion_matrix(y_test, y_pred_rf)
print("\nConfusion Matrix:\n", rf_cm)

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_rf))

"""Sau khi huấn luyện, mô hình Random Forest được sử dụng để dự đoán trên tập test.

Kết quả thu được:
- Accuracy ≈ 0.70
- Các chỉ số Precision, Recall và F1-score đều xấp xỉ 0.70

-> Nhận xét:  
Random Forest cho kết quả cao hơn Decision Tree một chút.  
Mô hình hoạt động ổn định và có khả năng phân loại tương đối tốt giữa hai lớp.

Tuy nhiên, mức cải thiện không quá lớn, cho thấy cả hai mô hình đều đã tận dụng tốt các đặc trưng đầu vào.

## 🟦 Hình 16: Ma trận nhầm lẫn Random Forest
"""

disp = ConfusionMatrixDisplay(confusion_matrix=rf_cm, display_labels=["Dislike", "Like"])
disp.plot()
plt.title("Random Forest - Confusion Matrix")
plt.show()

"""Nhóm sử dụng ma trận nhầm lẫn để đánh giá chi tiết khả năng phân loại của mô hình Random Forest.

Kết quả cho thấy:
- Dự đoán đúng lớp “không thích”: 7286
- Dự đoán đúng lớp “thích”: 6864
- Dự đoán sai từ “không thích” sang “thích”: 3166
- Dự đoán sai từ “thích” sang “không thích”: 2852

-> Nhận xét:  
Ma trận nhầm lẫn cho thấy mô hình Random Forest đã phân loại khá tốt ở cả hai lớp.  
Số lượng dự đoán đúng ở cả hai lớp đều cao, đồng thời số lượng nhầm lẫn đã giảm so với Decision Tree.

Điều này cho thấy Random Forest có khả năng nhận diện tốt hơn một chút, đặc biệt trong việc dự đoán các trường hợp người dùng thích phim.

## 🟦 Hình 17: Độ quan trọng thuộc tính
"""

rf_importance = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": rf_model.feature_importances_
}).sort_values(by="Importance", ascending=False)

print(rf_importance.head(10))

top_rf = rf_importance.head(10)

plt.figure(figsize=(10, 6))
plt.barh(top_rf["Feature"], top_rf["Importance"])
plt.gca().invert_yaxis()
plt.xlabel("Importance")
plt.ylabel("Feature")
plt.title("Top 10 thuộc tính quan trọng - Random Forest")
plt.show()

"""Nhóm tiến hành tính toán độ quan trọng của các thuộc tính trong mô hình Random Forest.

Kết quả cho thấy:
- movie_avg_rating (~0.54)
- user_avg_rating (~0.38)
- một số thể loại như Drama, Comedy, Crime có ảnh hưởng nhỏ hơn

-> Nhận xét:  
Kết quả cho thấy các đặc trưng liên quan đến hành vi người dùng (user_avg_rating) và chất lượng phim (movie_avg_rating) có ảnh hưởng lớn nhất đến dự đoán. Điều này phù hợp với thực tế, khi quyết định “thích” hay “không thích” của người dùng thường phụ thuộc vào xu hướng cá nhân và mức độ phổ biến của bộ phim hơn là chỉ dựa vào thể loại.
  
So với Decision Tree, Random Forest có xu hướng phân bổ độ quan trọng đồng đều hơn giữa các thuộc tính.

Điều này cho thấy mô hình đã khai thác thông tin từ nhiều đặc trưng hơn, giúp tăng tính ổn định và độ chính xác.

# PHẦN SO SÁNH VÀ KẾT LUẬN

## 🟦 Hình 18: So sánh hai mô hình
"""

comparison = pd.DataFrame({
    "Model": ["Decision Tree", "Random Forest"],
    "Accuracy": [dt_acc, rf_acc]
})

comparison

plt.figure(figsize=(7, 4))
plt.bar(comparison["Model"], comparison["Accuracy"])
plt.ylim(0, 1)
plt.title("So sánh Accuracy")
plt.ylabel("Accuracy")
plt.show()

"""Nhóm tiến hành so sánh kết quả giữa hai mô hình Decision Tree và Random Forest.

Kết quả đạt được:
- Decision Tree: Accuracy ≈ 0.699
- Random Forest: Accuracy ≈ 0.702

-> Nhận xét:  
Random Forest cho kết quả cao hơn một chút so với Decision Tree.  
Tuy nhiên, mức chênh lệch không lớn, cho thấy cả hai mô hình đều hoạt động khá tốt trên bộ dữ liệu này.

## 🔹 Kết luận

Qua quá trình thực nghiệm, có thể thấy rằng cả hai mô hình đều đạt độ chính xác khoảng 70% và có khả năng dự đoán tương đối tốt.

Decision Tree có ưu điểm là đơn giản, dễ hiểu và dễ trực quan hóa.  
Trong khi đó, Random Forest có ưu điểm là ổn định hơn và cho kết quả tốt hơn một chút.

Nhìn chung, Random Forest là lựa chọn phù hợp hơn trong bài toán này. Tuy nhiên, Decision Tree vẫn có giá trị trong trường hợp cần mô hình dễ giải thích và trực quan.
"""