# -*- coding: utf-8 -*-
"""Hierarchical Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aD9T-B52NiP1vOrJRYwewZjJuUfLY3_O
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from scipy.cluster.hierarchy import dendrogram, linkage
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import AgglomerativeClustering

file_path = 'movielens_full_converted.csv'
try:
    df = pd.read_csv(file_path)
    display(df.head(10))

except FileNotFoundError:
    print(f"Không tìm thấy file '{file_path}'")

df_genres = df.assign(genres=df['genres'].str.split('|')).explode('genres')

user_genre_matrix = df_genres.groupby(['userId', 'genres'])['rating'].mean().unstack()

user_genre_matrix = user_genre_matrix.fillna(0)

print("\nMa trận Người dùng - Thể loại (5 dòng đầu):")
display(user_genre_matrix.head())

scaler = StandardScaler()
user_genre_scaled = scaler.fit_transform(user_genre_matrix)

user_genre_scaled_df = pd.DataFrame(user_genre_scaled, index=user_genre_matrix.index, columns=user_genre_matrix.columns)

linked = linkage(user_genre_scaled, method='ward')

plt.figure(figsize=(16, 8))
plt.title('Biểu đồ Dendrogram - Phân cấp nhóm người dùng theo sở thích phim', fontsize=16)
plt.xlabel('Chỉ số Người dùng (Users)', fontsize=12)
plt.ylabel('Khoảng cách (Ward Distance)', fontsize=12)

dendrogram(linked,
           orientation='top',
           distance_sort='descending',
           show_leaf_counts=True,
           color_threshold=35)

plt.axhline(y=35, color='r', linestyle='--')
plt.text(0, 35, 'Ngưỡng cắt ≈ 4 cụm', color='red')

plt.show()

# Phân cụm Hierarchical Clustering

n_clusters = 4
hc_model = AgglomerativeClustering(n_clusters=n_clusters, metric='euclidean', linkage='ward')

cluster_labels = hc_model.fit_predict(user_genre_scaled)

user_genre_matrix['Cluster'] = cluster_labels

print(f"\nSố lượng người dùng trong mỗi cụm:")
print(user_genre_matrix['Cluster'].value_counts())

print("\nKết quả phân cụm (5 dòng đầu):")
display(user_genre_matrix[['Cluster']].head())

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

pca = PCA(n_components=3)
user_pca = pca.fit_transform(user_genre_scaled)

import pandas as pd
df_pca = pd.DataFrame(user_pca, columns=['PC1', 'PC2', 'PC3'])
df_pca['Cluster'] = cluster_labels

fig = plt.figure(figsize=(10, 7))
ax = fig.add_subplot(111, projection='3d')

scatter = ax.scatter(
    df_pca['PC1'],
    df_pca['PC2'],
    df_pca['PC3'],
    c=df_pca['Cluster'],
    cmap='viridis',
    s=30
)

ax.set_title("Phân cụm người dùng (3D Visualization)", fontsize=14)
ax.set_xlabel("PC1")
ax.set_ylabel("PC2")
ax.set_zlabel("PC3")

plt.show()

print("Top 3 thể loại phim được yêu thích nhất theo từng nhóm:\n")
for cluster in range(n_clusters):
    top_genres = cluster_profiles.loc[cluster].sort_values(ascending=False).head(3)
    print(f"=== Nhóm {cluster} ===")
    print(top_genres.to_string())
    print("-" * 20)