# -*- coding: utf-8 -*-
"""KNN_VÀ_NAIVE_BAYES.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v3gJQd32aN3leMo1SD0Mt365nu0REQXg

**Hình 1 Upload file dữ liệu**
"""

from google.colab import files
uploaded = files.upload()

# ĐỌC DỮ LIỆU SAU KHI UPLOAD
# =====================================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('movielens_full_converted.csv')

print("Kích thước dữ liệu:", df.shape)
df.head(10)

# KHÁM PHÁ DỮ LIỆU
# =====================================================
print("Các cột:", df.columns)

print("\nThông tin dữ liệu:")
df.info()

print("\nGiá trị thiếu:")
print(df.isnull().sum())

print("\nThống kê rating:")
print(df['rating'].describe())

# =====================================================
# HÌNH 4 - TẠO NHÃN CLASSIFICATION
# =====================================================
df['liked'] = (df['rating'] >= 4.0).astype(int)

print(df['liked'].value_counts())
print(df['liked'].value_counts(normalize=True))

# =====================================================
#HÌNH 5 - TRỰC QUAN PHÂN BỐ LỚP#
sns.countplot(x='liked', data=df)
plt.xticks([0, 1], ['Không thích', 'Thích'])
plt.title('Phân bố lớp liked')
plt.show()

# =====================================================
# HÌNH 6 - TIỀN XỬ LÝ DỮ LIỆU
from sklearn.preprocessing import MultiLabelBinarizer

# Trích xuất năm phát hành từ title
df['year'] = df['title'].str.extract(r'\((\d{4})\)')
df['year'] = pd.to_numeric(df['year'], errors='coerce')
df['year'] = df['year'].fillna(df['year'].median())

# Tạo biến có tag hay không
df['has_tag'] = df['tag'].notna().astype(int)

# Tách thể loại phim
df['genres_list'] = df['genres'].str.split('|')

# One-hot encoding cho genres
mlb = MultiLabelBinarizer()
genres_encoded = pd.DataFrame(
    mlb.fit_transform(df['genres_list']),
    columns=mlb.classes_,
    index=df.index
)

# Gộp các đặc trưng
X_full = pd.concat([
    df[['userId', 'movieId', 'year', 'has_tag']],
    genres_encoded
], axis=1)

y_full = df['liked']

print("Số lượng đặc trưng:", X_full.shape[1])
X_full.head()

# =====================================================
#HÌNH 7 - LẤY MẪU DỮ LIỆU ĐỂ CHẠY NHANH HƠN
from sklearn.model_selection import train_test_split

sample_df, _ = train_test_split(
    df,
    train_size=20000,
    stratify=df['liked'],
    random_state=42
)

X = pd.concat([
    sample_df[['userId', 'movieId', 'year', 'has_tag']],
    genres_encoded.loc[sample_df.index]
], axis=1)

y = sample_df['liked']

print("Kích thước dữ liệu dùng để huấn luyện:", X.shape)
print(y.value_counts(normalize=True))

# =====================================================
# HÌNH 8 - CHIA TRAIN/TEST
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

print("Train size:", X_train.shape)
print("Test size:", X_test.shape)

"""THUẬT TOÁN KNN"""

# =====================================================
# HÌNH 9 - CHUẨN HÓA DỮ LIỆU CHO KNN
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# =========================================================
# HÌNH 10 - CHỌN K BẰNG CROSS VALIDATION
# =========================================================
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score

k_values = range(1, 16)
cv_scores = []

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    scores = cross_val_score(knn, X_train_scaled, y_train, cv=5, scoring='accuracy')
    cv_scores.append(scores.mean())

best_k = k_values[cv_scores.index(max(cv_scores))]
print("Best K:", best_k)
print("Best CV Accuracy:", max(cv_scores))
##Biểu đồ
import matplotlib.pyplot as plt

plt.plot(list(k_values), cv_scores, marker='o')
plt.xlabel('Giá trị K')
plt.ylabel('Cross-Validation Accuracy')
plt.title('Chọn K tối ưu bằng Cross Validation')
plt.show()

# Huấn luyện lại mô hình với K tốt nhất
knn = KNeighborsClassifier(n_neighbors=11)
knn.fit(X_train_scaled, y_train)

y_pred_knn = knn.predict(X_test_scaled)

# =====================================================
#HÌNH 11 - ĐÁNH GIÁ KNN
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("KNN Accuracy:", accuracy_score(y_test, y_pred_knn))
print("\nClassification Report - KNN:")
print(classification_report(y_test, y_pred_knn))

cm_knn = confusion_matrix(y_test, y_pred_knn)
print("Confusion Matrix - KNN:")
print(cm_knn)

# =====================================================
# HÌNH 12 - VẼ CONFUSION MATRIX CHO KNN
sns.heatmap(cm_knn, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix - KNN')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

"""THUẬT TOÁN NAIVE BYES"""

#HÌNH 13 - HUẤN LUYỆN NAIVE BAYES
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
nb.fit(X_train, y_train)

y_pred_nb = nb.predict(X_test)

# =====================================================
#HÌNH 14 - ĐÁNH GIÁ NAIVE BAYES
print("Naive Bayes Accuracy:", accuracy_score(y_test, y_pred_nb))
print("\nClassification Report - Naive Bayes:")
print(classification_report(y_test, y_pred_nb))

cm_nb = confusion_matrix(y_test, y_pred_nb)
print("Confusion Matrix - Naive Bayes:")
print(cm_nb)

# ====================================================
# HÌNH 15 - VẼ CONFUSION MATRIX CHO NAIVE BAYES
sns.heatmap(cm_nb, annot=True, fmt='d', cmap='Oranges')
plt.title('Confusion Matrix - Naive Bayes')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

#HÌNH 16 - So sánh 2 thuật toán
print("KNN Accuracy:", accuracy_score(y_test, y_pred_knn))
print("Naive Bayes Accuracy:", accuracy_score(y_test, y_pred_nb))