# -*- coding: utf-8 -*-
"""K-MEANS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GMyy_CQT4LBysXtRw4qFKFmKWPk9SBcv
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import MultiLabelBinarizer, StandardScaler
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.metrics import silhouette_score
from scipy.cluster.hierarchy import dendrogram, linkage
#Đọc dữ liệu
df = pd.read_csv("movielens_full_converted.csv")

#Xem thông tin
print("Kích thước dữ liệu:", df.shape)
print("\n5 dòng đầu:")
display(df.head())

print("\nThông tin dữ liệu:")
print(df.info())

print("\nKiểm tra giá trị thiếu:")
print(df.isnull().sum())

#Giữ lại các cột cần thiết
df = df[['userId', 'rating', 'genres']].copy()
display(df.head())

# Tách genres thành danh sách
df['genres_list'] = df['genres'].apply(lambda x: x.split('|'))
print("Genres sau khi tách:")
display(df.head())

# ==============================
# ONE-HOT ENCODING CHO GENRES
# ==============================
mlb = MultiLabelBinarizer()
genre_encoded = pd.DataFrame(
    mlb.fit_transform(df['genres_list']),
    columns=mlb.classes_,
    index=df.index
)
print("Các thể loại phim:")
print(mlb.classes_)
print("\nMa trận one-hot của genres:")
display(genre_encoded.head())

# TẠO ĐẶC TRƯNG SỞ THÍCH NGƯỜI DÙNG THEO THỂ LOẠI
# Nhân rating với genre
genre_rating = genre_encoded.mul(df['rating'], axis=0)

# Gộp userId vào
genre_rating['userId'] = df['userId']
genre_encoded['userId'] = df['userId']

# Tính tổng rating và số lần
user_genre_sum = genre_rating.groupby('userId').sum()
user_genre_count = genre_encoded.groupby('userId').sum()

# Tính trung bình
user_genre_profile = user_genre_sum.div(user_genre_count.replace(0, np.nan)
).fillna(0)

# In kết quả
print("Kích thước:", user_genre_profile.shape)
display(user_genre_profile.head())

#Chuẩn hoá dữ liệu
#Khởi tạo và tính toán chuẩn hóa
scaler = StandardScaler()
X_scaled = scaler.fit_transform(user_genre_profile)

print(f"Kích thước dữ liệu sau chuẩn hóa: {X_scaled.shape}")

# Chuyển đổi mảng NumPy sang DataFrame để dễ quan sát tên cột
X_scaled_df = pd.DataFrame(X_scaled, columns=user_genre_profile.columns)

# Hiển thị kết quả
display(X_scaled_df.head())

# ==============================
# TÌM SỐ CỤM K PHÙ HỢP CHO K-MEANS
# ==============================
inertia_values = []
silhouette_values = []
K_range = range(2, 11)

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(X_scaled)

    inertia_values.append(kmeans.inertia_)
    silhouette_values.append(silhouette_score(X_scaled, labels))

# Vẽ Elbow Method
plt.figure(figsize=(8,5))
plt.plot(list(K_range), inertia_values, marker='o')
plt.title("Elbow Method for K-Means")
plt.xlabel("Number of Clusters (k)")
plt.ylabel("Inertia")
plt.grid(True)
plt.show()

# Vẽ Silhouette Score
plt.figure(figsize=(8,5))
plt.plot(list(K_range), silhouette_values, marker='o')
plt.title("Silhouette Score for K-Means")
plt.xlabel("Number of Clusters (k)")
plt.ylabel("Silhouette Score")
plt.grid(True)
plt.show()

# In bảng kết quả
result_k = pd.DataFrame({
    'k': list(K_range),
    'Inertia': inertia_values,
    'Silhouette Score': silhouette_values
})
display(result_k)

# ==============================
# CHẠY K-MEANS VỚI K TỐI ƯU
# Chọn K=4
optimal_k = 4
kmeans = KMeans(n_clusters=optimal_k, random_state=42, n_init=10)
kmeans_labels = kmeans.fit_predict(X_scaled)
# Gắn nhãn cụm vào hồ sơ người dùng
user_genre_profile_kmeans = user_genre_profile.copy()
user_genre_profile_kmeans['Cluster'] = kmeans_labels
print("Số lượng user trong mỗi cụm:")
print(user_genre_profile_kmeans['Cluster'].value_counts().sort_index())
display(user_genre_profile_kmeans.head())

# ==============================
# PHÂN TÍCH ĐẶC ĐIỂM TỪNG CỤM K-MEANS
# ==============================
cluster_profile = user_genre_profile_kmeans.groupby('Cluster').mean()
print("Trung bình mức yêu thích thể loại của từng cụm:")
display(cluster_profile)
# Với mỗi cụm, lấy ra 3 thể loại được yêu thích nhất
for cluster_id in cluster_profile.index:
    print(f"\nCụm {cluster_id} - Top 3 thể loại nổi bật:")
    top_genres = cluster_profile.loc[cluster_id].sort_values(ascending=False).head(3)
    print(top_genres)