{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "af573849",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "#Đọc dữ liệu từ file CSV (đảm bảo các file csv đang để cùng thư mục với file .ipynb)\n",
    "movies = pd.read_csv('movies.csv')\n",
    "ratings = pd.read_csv('ratings.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "9b7cdba3",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Tích hợp dữ liệu (Merge)\n",
    "# Bảng movies và ratings liên kết với nhau qua mã chung là 'movieId'\n",
    "flat_table = pd.merge(ratings, movies, on='movieId', how='inner')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "a6e3e121",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>userId</th>\n",
       "      <th>movieId</th>\n",
       "      <th>rating</th>\n",
       "      <th>timestamp</th>\n",
       "      <th>title</th>\n",
       "      <th>genres</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>4.0</td>\n",
       "      <td>964982703</td>\n",
       "      <td>Toy Story (1995)</td>\n",
       "      <td>Adventure|Animation|Children|Comedy|Fantasy</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1</td>\n",
       "      <td>3</td>\n",
       "      <td>4.0</td>\n",
       "      <td>964981247</td>\n",
       "      <td>Grumpier Old Men (1995)</td>\n",
       "      <td>Comedy|Romance</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1</td>\n",
       "      <td>6</td>\n",
       "      <td>4.0</td>\n",
       "      <td>964982224</td>\n",
       "      <td>Heat (1995)</td>\n",
       "      <td>Action|Crime|Thriller</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1</td>\n",
       "      <td>47</td>\n",
       "      <td>5.0</td>\n",
       "      <td>964983815</td>\n",
       "      <td>Seven (a.k.a. Se7en) (1995)</td>\n",
       "      <td>Mystery|Thriller</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1</td>\n",
       "      <td>50</td>\n",
       "      <td>5.0</td>\n",
       "      <td>964982931</td>\n",
       "      <td>Usual Suspects, The (1995)</td>\n",
       "      <td>Crime|Mystery|Thriller</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   userId  movieId  rating  timestamp                        title  \\\n",
       "0       1        1     4.0  964982703             Toy Story (1995)   \n",
       "1       1        3     4.0  964981247      Grumpier Old Men (1995)   \n",
       "2       1        6     4.0  964982224                  Heat (1995)   \n",
       "3       1       47     5.0  964983815  Seven (a.k.a. Se7en) (1995)   \n",
       "4       1       50     5.0  964982931   Usual Suspects, The (1995)   \n",
       "\n",
       "                                        genres  \n",
       "0  Adventure|Animation|Children|Comedy|Fantasy  \n",
       "1                               Comedy|Romance  \n",
       "2                        Action|Crime|Thriller  \n",
       "3                             Mystery|Thriller  \n",
       "4                       Crime|Mystery|Thriller  "
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df = flat_table\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "447ff298",
   "metadata": {},
   "outputs": [],
   "source": [
    "from mlxtend.frequent_patterns import fpgrowth\n",
    "from mlxtend.frequent_patterns import association_rules"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "c7b5c843",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Đang lọc dữ liệu...\n"
     ]
    }
   ],
   "source": [
    "# BƯỚC 1: TIỀN XỬ LÝ DỮ LIỆU (Định nghĩa lại \"Giỏ hàng\")\n",
    "print(\"Đang lọc dữ liệu...\")\n",
    "# Chỉ giữ lại những đánh giá >= 4.0 (Bộ phim mà User thực sự yêu thích)\n",
    "df_liked = flat_table[flat_table['rating'] >= 4.0]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "c2f5c4f9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "        userId  movieId  rating   timestamp  \\\n",
      "0            1        1     4.0   964982703   \n",
      "1            1        3     4.0   964981247   \n",
      "2            1        6     4.0   964982224   \n",
      "3            1       47     5.0   964983815   \n",
      "4            1       50     5.0   964982931   \n",
      "...        ...      ...     ...         ...   \n",
      "100830     610   166528     4.0  1493879365   \n",
      "100831     610   166534     4.0  1493848402   \n",
      "100832     610   168248     5.0  1493850091   \n",
      "100833     610   168250     5.0  1494273047   \n",
      "100834     610   168252     5.0  1493846352   \n",
      "\n",
      "                                      title  \\\n",
      "0                          Toy Story (1995)   \n",
      "1                   Grumpier Old Men (1995)   \n",
      "2                               Heat (1995)   \n",
      "3               Seven (a.k.a. Se7en) (1995)   \n",
      "4                Usual Suspects, The (1995)   \n",
      "...                                     ...   \n",
      "100830  Rogue One: A Star Wars Story (2016)   \n",
      "100831                         Split (2017)   \n",
      "100832        John Wick: Chapter Two (2017)   \n",
      "100833                       Get Out (2017)   \n",
      "100834                         Logan (2017)   \n",
      "\n",
      "                                             genres  \n",
      "0       Adventure|Animation|Children|Comedy|Fantasy  \n",
      "1                                    Comedy|Romance  \n",
      "2                             Action|Crime|Thriller  \n",
      "3                                  Mystery|Thriller  \n",
      "4                            Crime|Mystery|Thriller  \n",
      "...                                             ...  \n",
      "100830              Action|Adventure|Fantasy|Sci-Fi  \n",
      "100831                        Drama|Horror|Thriller  \n",
      "100832                        Action|Crime|Thriller  \n",
      "100833                                       Horror  \n",
      "100834                                Action|Sci-Fi  \n",
      "\n",
      "[48580 rows x 6 columns]\n"
     ]
    }
   ],
   "source": [
    "print(df_liked)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "5b2a369f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Đang chuyển đổi thành Ma trận One-Hot Encoding...\n"
     ]
    }
   ],
   "source": [
    "# BƯỚC 2: MÃ HÓA DỮ LIỆU (Data Transformation)\n",
    "print(\"Đang chuyển đổi thành Ma trận One-Hot Encoding...\")\n",
    "# Gom nhóm theo userId (hóa đơn) và title (món hàng). \n",
    "# Nếu user có xem phim đó, đánh số 1, ngược lại điền số 0 (fillna(0))\n",
    "basket = df_liked.pivot_table(index='userId', columns='title', values='rating', aggfunc='size', fill_value=0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "cba22762",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th>title</th>\n",
       "      <th>'71 (2014)</th>\n",
       "      <th>'Hellboy': The Seeds of Creation (2004)</th>\n",
       "      <th>'Salem's Lot (2004)</th>\n",
       "      <th>'Til There Was You (1997)</th>\n",
       "      <th>'burbs, The (1989)</th>\n",
       "      <th>(500) Days of Summer (2009)</th>\n",
       "      <th>*batteries not included (1987)</th>\n",
       "      <th>...And Justice for All (1979)</th>\n",
       "      <th>00 Schneider - Jagd auf Nihil Baxter (1994)</th>\n",
       "      <th>1-900 (06) (1994)</th>\n",
       "      <th>...</th>\n",
       "      <th>Zombieland (2009)</th>\n",
       "      <th>Zookeeper (2011)</th>\n",
       "      <th>Zoolander (2001)</th>\n",
       "      <th>Zootopia (2016)</th>\n",
       "      <th>Zulu (1964)</th>\n",
       "      <th>[REC] (2007)</th>\n",
       "      <th>[REC]² (2009)</th>\n",
       "      <th>eXistenZ (1999)</th>\n",
       "      <th>xXx (2002)</th>\n",
       "      <th>¡Three Amigos! (1986)</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>userId</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 6297 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "title   '71 (2014)  'Hellboy': The Seeds of Creation (2004)  \\\n",
       "userId                                                        \n",
       "1                0                                        0   \n",
       "2                0                                        0   \n",
       "3                0                                        0   \n",
       "4                0                                        0   \n",
       "5                0                                        0   \n",
       "\n",
       "title   'Salem's Lot (2004)  'Til There Was You (1997)  'burbs, The (1989)  \\\n",
       "userId                                                                       \n",
       "1                         0                          0                   0   \n",
       "2                         0                          0                   0   \n",
       "3                         0                          0                   0   \n",
       "4                         0                          0                   0   \n",
       "5                         0                          0                   0   \n",
       "\n",
       "title   (500) Days of Summer (2009)  *batteries not included (1987)  \\\n",
       "userId                                                                \n",
       "1                                 0                               0   \n",
       "2                                 0                               0   \n",
       "3                                 0                               0   \n",
       "4                                 0                               0   \n",
       "5                                 0                               0   \n",
       "\n",
       "title   ...And Justice for All (1979)  \\\n",
       "userId                                  \n",
       "1                                   0   \n",
       "2                                   0   \n",
       "3                                   0   \n",
       "4                                   0   \n",
       "5                                   0   \n",
       "\n",
       "title   00 Schneider - Jagd auf Nihil Baxter (1994)  1-900 (06) (1994)  ...  \\\n",
       "userId                                                                  ...   \n",
       "1                                                 0                  0  ...   \n",
       "2                                                 0                  0  ...   \n",
       "3                                                 0                  0  ...   \n",
       "4                                                 0                  0  ...   \n",
       "5                                                 0                  0  ...   \n",
       "\n",
       "title   Zombieland (2009)  Zookeeper (2011)  Zoolander (2001)  \\\n",
       "userId                                                          \n",
       "1                       0                 0                 0   \n",
       "2                       0                 0                 0   \n",
       "3                       0                 0                 0   \n",
       "4                       0                 0                 0   \n",
       "5                       0                 0                 0   \n",
       "\n",
       "title   Zootopia (2016)  Zulu (1964)  [REC] (2007)  [REC]² (2009)  \\\n",
       "userId                                                              \n",
       "1                     0            0             0              0   \n",
       "2                     0            0             0              0   \n",
       "3                     0            0             0              0   \n",
       "4                     0            0             0              0   \n",
       "5                     0            0             0              0   \n",
       "\n",
       "title   eXistenZ (1999)  xXx (2002)  ¡Three Amigos! (1986)  \n",
       "userId                                                      \n",
       "1                     0           0                      1  \n",
       "2                     0           0                      0  \n",
       "3                     0           0                      0  \n",
       "4                     0           0                      0  \n",
       "5                     0           0                      0  \n",
       "\n",
       "[5 rows x 6297 columns]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "display(basket.head(5))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "96051dbd",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Đang chạy thuật toán FP-Growth...\n",
      "Các tập phổ biến:\n",
      "        support                                           itemsets\n",
      "0      0.408867                   frozenset({Forrest Gump (1994)})\n",
      "1      0.369458      frozenset({Silence of the Lambs, The (1991)})\n",
      "2      0.364532                    frozenset({Matrix, The (1999)})\n",
      "3      0.330049  frozenset({Star Wars: Episode IV - A New Hope ...\n",
      "4      0.293924                     frozenset({Fight Club (1999)})\n",
      "...         ...                                                ...\n",
      "33184  0.052545  frozenset({Lord of the Rings: The Return of th...\n",
      "33185  0.050903  frozenset({Sin City (2005), Lord of the Rings:...\n",
      "33186  0.050903  frozenset({Lord of the Rings: The Return of th...\n",
      "33187  0.050903  frozenset({Sin City (2005), Silence of the Lam...\n",
      "33188  0.050903  frozenset({Sin City (2005), Pulp Fiction (1994...\n",
      "\n",
      "[33189 rows x 2 columns]\n"
     ]
    }
   ],
   "source": [
    "# BƯỚC 3: CHẠY THUẬT TOÁN FP-GROWTH (Modeling)\n",
    "print(\"Đang chạy thuật toán FP-Growth...\")\n",
    "basket_encoded = basket > 0\n",
    "# Đặt Minsup = 0.05 (Tức là tập phim phải được ít nhất 5% tổng số user cùng thích)\n",
    "# Thuật toán sẽ dùng FP-Tree để nén dữ liệu và tìm tập phổ biến [1, 2]\n",
    "frequent_itemsets = fpgrowth(basket_encoded, min_support=0.05, use_colnames=True)\n",
    "print(\"Các tập phổ biến:\")\n",
    "print(frequent_itemsets)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "735b8bea",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Đang sinh các luật kết hợp...\n",
      "Các luật kết hợp có Lift > 1:481100\n"
     ]
    }
   ],
   "source": [
    "# BƯỚC 4: SINH LUẬT KẾT HỢP & LỌC BẰNG LIFT (Association Rules)\n",
    "print(\"Đang sinh các luật kết hợp...\")\n",
    "# Sinh luật từ các tập phổ biến, sử dụng chỉ số LIFT làm hệ quy chiếu\n",
    "# Chỉ lấy những luật có Lift > 1 (Chứng tỏ hai phim thực sự có tương quan dương với nhau) [3, 4]\n",
    "rules = association_rules(frequent_itemsets, metric=\"lift\", min_threshold=1.0)\n",
    "\n",
    "# Sắp xếp các luật theo chỉ số Lift giảm dần để xem luật nào mạnh nhất\n",
    "rules = rules.sort_values('lift', ascending=False)\n",
    "print(\"Các luật kết hợp có Lift > 1:\" + str(rules[rules['lift'] > 1].shape[0]))  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "d7e21593",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "HOÀN THÀNH! Dưới đây là Top 10 luật Gợi ý phim xuất sắc nhất:\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>antecedents</th>\n",
       "      <th>consequents</th>\n",
       "      <th>support</th>\n",
       "      <th>confidence</th>\n",
       "      <th>lift</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>476506</th>\n",
       "      <td>frozenset({Star Wars: Episode V - The Empire S...</td>\n",
       "      <td>frozenset({Kill Bill: Vol. 2 (2004), Matrix, T...</td>\n",
       "      <td>0.052545</td>\n",
       "      <td>0.780488</td>\n",
       "      <td>13.203252</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>476503</th>\n",
       "      <td>frozenset({Kill Bill: Vol. 2 (2004), Matrix, T...</td>\n",
       "      <td>frozenset({Star Wars: Episode V - The Empire S...</td>\n",
       "      <td>0.052545</td>\n",
       "      <td>0.888889</td>\n",
       "      <td>13.203252</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>476521</th>\n",
       "      <td>frozenset({Kill Bill: Vol. 1 (2003), Star Wars...</td>\n",
       "      <td>frozenset({Kill Bill: Vol. 2 (2004), Star Wars...</td>\n",
       "      <td>0.052545</td>\n",
       "      <td>0.780488</td>\n",
       "      <td>12.846407</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>476517</th>\n",
       "      <td>frozenset({Kill Bill: Vol. 2 (2004), Star Wars...</td>\n",
       "      <td>frozenset({Star Wars: Episode V - The Empire S...</td>\n",
       "      <td>0.052545</td>\n",
       "      <td>0.780488</td>\n",
       "      <td>12.846407</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>476488</th>\n",
       "      <td>frozenset({Kill Bill: Vol. 2 (2004), Star Wars...</td>\n",
       "      <td>frozenset({Kill Bill: Vol. 1 (2003), Star Wars...</td>\n",
       "      <td>0.052545</td>\n",
       "      <td>0.864865</td>\n",
       "      <td>12.846407</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>476492</th>\n",
       "      <td>frozenset({Star Wars: Episode V - The Empire S...</td>\n",
       "      <td>frozenset({Kill Bill: Vol. 2 (2004), Star Wars...</td>\n",
       "      <td>0.052545</td>\n",
       "      <td>0.864865</td>\n",
       "      <td>12.846407</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>476487</th>\n",
       "      <td>frozenset({Kill Bill: Vol. 2 (2004), Star Wars...</td>\n",
       "      <td>frozenset({Star Wars: Episode V - The Empire S...</td>\n",
       "      <td>0.052545</td>\n",
       "      <td>0.969697</td>\n",
       "      <td>12.837945</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>476522</th>\n",
       "      <td>frozenset({Star Wars: Episode V - The Empire S...</td>\n",
       "      <td>frozenset({Kill Bill: Vol. 2 (2004), Star Wars...</td>\n",
       "      <td>0.052545</td>\n",
       "      <td>0.695652</td>\n",
       "      <td>12.837945</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>476504</th>\n",
       "      <td>frozenset({Kill Bill: Vol. 2 (2004), Star Wars...</td>\n",
       "      <td>frozenset({Kill Bill: Vol. 1 (2003), Star Wars...</td>\n",
       "      <td>0.052545</td>\n",
       "      <td>0.800000</td>\n",
       "      <td>12.821053</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>476505</th>\n",
       "      <td>frozenset({Kill Bill: Vol. 1 (2003), Star Wars...</td>\n",
       "      <td>frozenset({Kill Bill: Vol. 2 (2004), Star Wars...</td>\n",
       "      <td>0.052545</td>\n",
       "      <td>0.842105</td>\n",
       "      <td>12.821053</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                              antecedents  \\\n",
       "476506  frozenset({Star Wars: Episode V - The Empire S...   \n",
       "476503  frozenset({Kill Bill: Vol. 2 (2004), Matrix, T...   \n",
       "476521  frozenset({Kill Bill: Vol. 1 (2003), Star Wars...   \n",
       "476517  frozenset({Kill Bill: Vol. 2 (2004), Star Wars...   \n",
       "476488  frozenset({Kill Bill: Vol. 2 (2004), Star Wars...   \n",
       "476492  frozenset({Star Wars: Episode V - The Empire S...   \n",
       "476487  frozenset({Kill Bill: Vol. 2 (2004), Star Wars...   \n",
       "476522  frozenset({Star Wars: Episode V - The Empire S...   \n",
       "476504  frozenset({Kill Bill: Vol. 2 (2004), Star Wars...   \n",
       "476505  frozenset({Kill Bill: Vol. 1 (2003), Star Wars...   \n",
       "\n",
       "                                              consequents   support  \\\n",
       "476506  frozenset({Kill Bill: Vol. 2 (2004), Matrix, T...  0.052545   \n",
       "476503  frozenset({Star Wars: Episode V - The Empire S...  0.052545   \n",
       "476521  frozenset({Kill Bill: Vol. 2 (2004), Star Wars...  0.052545   \n",
       "476517  frozenset({Star Wars: Episode V - The Empire S...  0.052545   \n",
       "476488  frozenset({Kill Bill: Vol. 1 (2003), Star Wars...  0.052545   \n",
       "476492  frozenset({Kill Bill: Vol. 2 (2004), Star Wars...  0.052545   \n",
       "476487  frozenset({Star Wars: Episode V - The Empire S...  0.052545   \n",
       "476522  frozenset({Kill Bill: Vol. 2 (2004), Star Wars...  0.052545   \n",
       "476504  frozenset({Kill Bill: Vol. 1 (2003), Star Wars...  0.052545   \n",
       "476505  frozenset({Kill Bill: Vol. 2 (2004), Star Wars...  0.052545   \n",
       "\n",
       "        confidence       lift  \n",
       "476506    0.780488  13.203252  \n",
       "476503    0.888889  13.203252  \n",
       "476521    0.780488  12.846407  \n",
       "476517    0.780488  12.846407  \n",
       "476488    0.864865  12.846407  \n",
       "476492    0.864865  12.846407  \n",
       "476487    0.969697  12.837945  \n",
       "476522    0.695652  12.837945  \n",
       "476504    0.800000  12.821053  \n",
       "476505    0.842105  12.821053  "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# BƯỚC 5: ỨNG DỤNG THỰC TẾ (Xem kết quả)\n",
    "print(\"HOÀN THÀNH! Dưới đây là Top 10 luật Gợi ý phim xuất sắc nhất:\")\n",
    "# Hiển thị các cột quan trọng nhất: Phim A (Antecedents), Phim B (Consequents), Support, Confidence, Lift\n",
    "display(rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']].head(10))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
